### ISSUE TITLE
updated .clang_complete doesn't seem to take effect after :edit!

### ISSUE THREAD

**Issue by damnskippy** [Rip-Rip/clang_complete#534] opened 2017-07-15 01:32 UTC
Seeing an odd issue and I'd like to confirm if anyone else is seeing it.
.clang_complete file is present, and clang_complete functionality works as expected.
But when I update the .clang_complete_file because it is either not there, or is not correct, and then I reload the source file in vim via ":edit!", it doesn't seem to take effect.
For instance auto complete with '.' or '->' doesn't work after the reload.
Same for GotoDeclaration(), ClangUpdateQuickfix(), etc.
If I quit and relaunch vim to open the same source file, all is fine, things work as expected.

Oddly enough, when I set g:clang_debug to 1, I see that after reloading the compiler args from the *new* .clang_complete file are in fact being used, as expected.  i.e. parseConfig() was redone correctly.
But somehow the clang_complete code still behaves as if doesn't know about these new options.  As if it's using some cached values from elsewhere??

Can anyone else confirm if they are seeing this work as expected?
Or provide some suggestions on triaging it?

Quick way to repro:
$ mv .clang_complete dummy
$ vim <source.c>
// clang_complete functionality won't work because there's no .clang_complete 
// C-z to suspend vim, or from another terminal:
$ mv dummy .clang_complete
// fg, or get back to vim terminal
// reload source by doing a ":edit!" 
// clang_complete at this point should work, but doesn't.
// quit vim and reopen the source and clang_complete will work now.
Thanks.

**Comment by damnskippy** [comment] 2017-07-15 02:36
Really my use case is that I have a tree with multiple subtrees.
At the root of each subtree I have a .clang_complete file specific to that subtree (and they are compiled differently).
I often need to switch between these subtrees, pretty much all the time.
Right now when I switch the old .clang_complete still seems to be in effect, even after doing a ":edit!" as specified in the doc.

```
foo
├── a
│   ├── .clang_complete
│   ├── 1
│   ├── 2
│   └── 3
├── b
│   ├── .clang_complete
│   ├── 1
│   ├── 2
│   └── 3
└── c
    ├── .clang_complete
    ├── 1
    ├── 2
    └── 3

```

**Comment by damnskippy** [comment] 2017-07-15 02:37
And this is what the doc says and I really hope I'm interpreting it correctly:
```
Note that as with other option sources, .clang_complete file is loaded and
parsed by the plugin only on buffer loading (or reloading, for example with
:edit! command). Thus no changes made to .clang_complete file after loading
source file into Vim's buffer will take effect until buffer will be closed and
opened again, reloaded or Vim is restarted.
```

**Comment by xaizek** [comment] 2017-07-15 09:40
There is in fact a cache of translation units, but compiler options aren't considered in it. Please see if the issue is fixed on `consider-args-on-caching` branch.

**Comment by damnskippy** [comment] 2017-07-15 14:27
Indeed this change does fix the issue - thanks so much for taking care of this. 
I did notice that on the consider-args-on-caching branch, calling ClangUpdateQuickFix() resulted in the following error.  I don't see this on the master, so I'm not sure if it's a regression caused by this change.
Thought I'd let you know.
```
Error detected while processing function ClangUpdateQuickFix[1]..<SNR>29_DoPeriodicQuickFix:
line    7:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/homes/damnskippy/.vim/bundle/clang_complete/plugin/libclang.py", line 366, in updateCurrentDiagnostics
    vim.current.buffer.name, timer, update = True)
  File "/homes/damnskippy/.vim/bundle/clang_complete/plugin/libclang.py", line 194, in getCurrentTranslationUnit
    tu.reparse([currentFile])
AttributeError: 'dict' object has no attribute 'reparse'

```

**Comment by xaizek** [comment] 2017-07-15 16:18
I forgot to update one line, did that and merged the branch into master, thanks.

**Closed** 2017-07-15 16:18 UTC
